# Site settings
title: SNCL - Ski Nautique Club Lausanne
email: admin@sncl.ch
description: > # ignore newlines
  Presentation webiste of the SNCL
# logo: /assets/img/logo.png

theme: jekyll-theme-minimal

gems:
  - jekyll-redirect-from
